# This is a basic workflow to help you get started with Actions
name: Build and Upload Conda Package

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Name'     
        required: true
        default: 'me'
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        conda install conda-build conda-verify anaconda-client
        $CONDA/bin/anaconda -h
    #$CONDA/bin/c
   # - name: Setup Miniconda
   #   uses: conda-incubator/setup-miniconda@v2.0.0
   # - name: Install conda packages
   #   run: |
    #    conda install conda-build conda-verify anaconda-client
    - name: Build
      run: |
        conda build -c conda-forge --output-folder . .
    - name: Upload
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        anaconda upload --label main noarch/*.tar.bz2
